name: Publish to Comfy Registry

on:
  push:
    branches: [ master ]
    paths: [ 'pyproject.toml' ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Publish to Comfy Registry
      uses: Comfy-Org/publish-node-action@main
      with:
        personal_access_token: ${{ secrets.REGISTRY_ACCESS_TOKEN }}